## This is a basic workflow to help you get started with Actions
#
#name: Publish website
#
## Controls when the action will run.
#on:
#  push:
#    branches: [main]
#
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
#
## A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
#  # This workflow contains a single job called "build"
#  publish-website:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v4
#
#      - uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#
#      - name: Push website
#        run: ./millw -i publishSite
#        env:
#          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}